ImageDrive/Controllers/TestImageController.cs
using ImageDrive.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImageDrive.Controllers
{
    public class TestImageController : Controller
    {
        // GET: TestImage
        public ActionResult Index()
        { 
            using (DBmodel dbmodel = new DBmodel())
            {
                return View(dbmodel.TBLimages.ToList());
            }
            
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(TBLimage tblimage)
        {
            string fileName = Path.GetFileNameWithoutExtension(tblimage.ImageFile.FileName);
            string extension = Path.GetExtension(tblimage.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            tblimage.Image = "../Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("../Image/"), fileName);
            tblimage.ImageFile.SaveAs(fileName);
            using (DBmodel db = new DBmodel())
            {
                if (db.TBLimages.Any(m => m.Image.Contains(tblimage.Image)))
                {
                    ViewBag.DuplicateMessage = "File Name Already Exist.!";
                    return View();
                }
                db.TBLimages.Add(tblimage);
                db.SaveChanges();
            }
            ModelState.Clear();
            ViewBag.SucessMessage = "Image Added Successfully!";
            return View();
        }
    }
}

ImageDrive/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Photo Gallery", "Login", "Account", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @*<ul class="nav navbar-nav">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("About", "About", "Home")</li>
            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
        </ul>*@


                @*<ul class="nav navbar-nav">
            <li>
                @Html.ActionLink("Create Image", "Create", "TestImage")

            </li>
            <li>
                @Html.ActionLink("Show Image", "Index", "TestImage")
            </li>
        </ul>*@

                @*<ul class="nav navbar-nav" style="float:right!important">*@
                @if (Session["Email"] == null)
                {
                    @*<ul class="nav navbar-nav">
                        <li>
                            @Html.ActionLink("Create Image", "Create", "TestImage")

                        </li>
                        <li>
                            @Html.ActionLink("Show Image", "Index", "TestImage")
                        </li>
                    </ul>*@
                }
                else
                {
                    @*<li>@Html.ActionLink("Signup", "Signup", "Home")</li>
            <li>@Html.ActionLink("Login", "Login", "Home")</li>*@
                }
                @*</ul>*@

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

<style>
    footer p {
        text-align: center;
    }
</style>

</html>